### ISSUE TITLE
Too few arguments to function `SentinelReplication::getConnection()` after upgrade to php 8.1

### ISSUE THREAD

**Issue by dakorpar** [predis/predis#786]
**Describe the bug**
Not really sure how that happens, butI have problems with sentinel, on random requests I get error (after upgrade to php 8.1 from 8.0), which doesn't make sense when looking into code...
Too few arguments to function [Predis\Connection\Aggregate\SentinelReplication::getConnection], 0 passed in [vendor/predis/predis/src/Connection/Aggregate/SentinelReplication.php on line 670] and exactly 1 expected, see screenshot

**To Reproduce**
looks like on random requests...

**Expected behavior**

**Versions (please complete the following information):**
 - Predis: 1.1.10
 - PHP 8.1.8
 - Redis Server [5.0.6]
 - OS: Centos 7.9.2009

**Additional context**

![image](https://user-images.githubusercontent.com/9303856/179481533-3e979a10-dcd2-4018-ae0a-fba20cb29e18.png)

**Comment by tillkruss** [comment]
Feel free to open a PR with a fix.

**Comment by dakorpar** [comment]
If only I could reproduce this and understand what happens, because parameter is allways passed:
![image](https://user-images.githubusercontent.com/9303856/179582211-ba178a0d-7d5b-45ad-a9d6-ef28b01da7e5.png)
Something feels really wierd about this and this happens on less then 1% of calls...

**Comment by Federkun** [comment]
I may experience something similar/related, but with guzzle; any chance you are using newrelic?

**Comment by dakorpar** [comment]
yep, we're using newrelic, but with 2.0 upgrade we're no longer experiencing this issue, so as far as I'm concerned this can be closed

**Comment by tillkruss** [comment]
Great, thanks for reporting!
